#!/bin/bash
#SBATCH --job-name=humanoid
#SBATCH --output=mila/out.txt
#SBATCH --error=mila/err.txt
#SBATCH --ntasks=1
#SBATCH --time=2-00:00:00
#SBATCH --mem=32Gb
#SBATCH --gres=gpu:1
#SBATCH --partition=unkillable

source ~/.bashrc
source mila/install.sh

if [ -z "$1" ]; then
    TEMPDIR_PREFIX="/tmp"
fi

# Print gpu configuration for this job
nvidia-smi
python -c "import torch; print('PyTorch: CUDA is available' if torch.cuda.is_available() else 'PyTorch: CUDA is not available')"
python -c "import jax; print('Jax: CUDA is available' if jax.default_backend() == 'gpu' else 'Jax: CUDA is not available')"

mkdir -p $SLURM_TMPDIR/Humanoid-MuJoCo
cp -rf * $SLURM_TMPDIR/Humanoid-MuJoCo/ 2> /dev/null

CURRENT_DIR=$(pwd)

# create background process which regularly copies back the folder
while true; do
    sleep 30
    echo " > Copying data to home folder"
    cp -rf $SLURM_TMPDIR/Humanoid-MuJoCo/data/* $CURRENT_DIR/data/ 2> /dev/null
done &

cd $SLURM_TMPDIR/Humanoid-MuJoCo
python benchmark.py --n-envs 1 > $CURRENT_DIR/benchmark_1.txt
python benchmark.py --n-envs 4 > $CURRENT_DIR/benchmark_4.txt
python benchmark.py --n-envs 8 > $CURRENT_DIR/benchmark_8.txt
python benchmark.py --n-envs 16 > $CURRENT_DIR/benchmark_16.txt
python benchmark.py --n-envs 32 > $CURRENT_DIR/benchmark_32.txt
python benchmark.py --n-envs 64 > $CURRENT_DIR/benchmark_64.txt
python benchmark.py --n-envs 128 > $CURRENT_DIR/benchmark_128.txt
python benchmark.py --n-envs 256 > $CURRENT_DIR/benchmark_256.txt