#!/bin/bash
#SBATCH --job-name=humanoid
#SBATCH --output=slurm/out.txt
#SBATCH --error=slurm/err.txt
#SBATCH --ntasks=1
#SBATCH --time=2-00:00:00
#SBATCH --mem=32Gb
#SBATCH --gres=gpu:1
#SBATCH --partition=unkillable

source ~/.bashrc
source slurm/install.sh

if [ -z "$1" ]; then
    TEMPDIR_PREFIX="/tmp"
fi

# Print gpu configuration for this job
nvidia-smi
python -c "import torch; print('PyTorch: CUDA is available' if torch.cuda.is_available() else 'PyTorch: CUDA is not available')"
python -c "import jax; print('Jax: CUDA is available' if jax.default_backend() == 'gpu' else 'Jax: CUDA is not available')"

mkdir -p $SLURM_TMPDIR/Humanoid-MuJoCo
cp -rf * $SLURM_TMPDIR/Humanoid-MuJoCo/ 2> /dev/null

CURRENT_DIR=$(pwd)

# create background process which regularly copies back the folder
while true; do
    sleep 30
    echo " > Copying data to home folder"
    cp -rf $SLURM_TMPDIR/Humanoid-MuJoCo/rl/data/* $CURRENT_DIR/rl/data/ 2> /dev/null
done &

cd $SLURM_TMPDIR/Humanoid-MuJoCo/rl && python train.py --silent
